export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_SUCEESS = "FETCH_MOVIES_SUCEESS";
export const FETCH_MOVIES_FAIL = "FETCH_MOVIES_FAIL";

export const FETCH_CAST = "FETCH_CAST";
export const FETCH_CAST_SUCEESS = "FETCH_CAST_SUCEESS";
export const FETCH_CAST_FAIL = "FETCH_CAST_FAIL";

export const FETCH_LOADMORE = "FETCH_LOADMORE";
export const FETCH_LOADMORE_SUCEESS = "FETCH_LOADMORE_SUCEESS";
export const FETCH_LOADMORE_FAIL = "FETCH_LOADMORE_FAIL";

export const FETCH_REFRESH = "FETCH_REFRESH";
export const FETCH_REFRESH_SUCEESS = "FETCH_REFRESH_SUCEESS";
export const FETCH_REFRESH_FAIL = "FETCH_REFRESH_FAIL";

export const FETCH_CAST_DETEAL = "FETCH_CAST_DETEAL";
export const FETCH_CAST_DETEAL_SUCEESS = "FETCH_CAST_DETEAL_SUCEESS";
export const FETCH_CAST_DETEAL_FAIL = "FETCH_CAST_DETEAL_FAIL";

export const FETCH_MOVIES_BY_CAST = "FETCH_MOVIES_BY_CAST";
export const FETCH_MOVIES_BY_CAST_SUCEESS = "FETCH_MOVIES_BY_CAST_SUCEESS";
export const FETCH_MOVIES_BY_CAST_FAIL = "FETCH_MOVIES_BY_CAST_FAIL";

export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const SEARCH_MOVIE_SUCEESS = "SEARCH_MOVIE_SUCEESS";
export const SEARCH_MOVIE_FAIL = "SEARCH_MOVIE_FAIL";

export const PLAY_VIDEO = "PLAY_VIDEO";
export const PLAY_VIDEO_SUCEESS = "PLAY_VIDEO_SUCEESS";
export const PLAY_VIDEO_FAIL = "PLAY_VIDEO_FAIL";

export const FETCH_GENRE_MOVIES = "FETCH_GENRE_MOVIES";
export const FETCH_GENRE_MOVIES_SUCEESS = "FETCH_GENRE_MOVIES_SUCEESS";
export const FETCH_GENRE_MOVIES_FAIL = "FETCH_GENRE_MOVIES_FAIL";

export const FETCH_TRENDING_MOVIES = "FETCH_TRENDING_MOVIES";
export const FETCH_TRENDING_MOVIES_SUCEESS = "FETCH_GENRE_MOVIES_SUCEESS";
export const FETCH_TRENDING_MOVIES_FAIL = "FETCH_GENRE_MOVIES_FAIL";

export const FETCH_COMMENT_MOVIES = "FETCH_COMMENT_MOVIES";
export const FETCH_COMMENT_MOVIES_SUCEESS = "FETCH_COMMENT_MOVIES_SUCEESS";
export const FETCH_COMMENT_MOVIES_FAIL = "FETCH_COMMENT_MOVIES_FAIL";