export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_SUCEESS = "FETCH_MOVIES_SUCEESS";
export const FETCH_MOVIES_FAIL = "FETCH_MOVIES_FAIL";

export const FETCH_CAST = "FETCH_CAST";
export const FETCH_CAST_SUCEESS = "FETCH_CAST_SUCEESS";
export const FETCH_CAST_FAIL = "FETCH_CAST_FAIL";
