export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_SUCEESS = "FETCH_MOVIES_SUCEESS";
export const FETCH_MOVIES_FAIL = "FETCH_MOVIES_FAIL";

export const FETCH_CAST = "FETCH_CAST";
export const FETCH_CAST_SUCEESS = "FETCH_CAST_SUCEESS";
export const FETCH_CAST_FAIL = "FETCH_CAST_FAIL";

export const FETCH_LOADMORE = "FETCH_LOADMORE";
export const FETCH_LOADMORE_SUCEESS = "FETCH_LOADMORE_SUCEESS";
export const FETCH_LOADMORE_FAIL = "FETCH_LOADMORE_FAIL";

export const FETCH_REFRESH = "FETCH_REFRESH";
export const FETCH_REFRESH_SUCEESS = "FETCH_REFRESH_SUCEESS";
export const FETCH_REFRESH_FAIL = "FETCH_REFRESH_FAIL";
